= A CLI focused on developer productivity

* Note: this is a work in progress.  

* **main branch is currently broken after latest upgrade to openrewrite - sorry, will fix asap.  Dec 13, 2022.**

* https://spring-projects-experimental.github.io/spring-cli/spring-cli/[Read the documentation] for info on *Installing* and *Getting Started*

== Build

NOTE: Use either JDK11 or JDK17

Normal build without _native_:
```
./gradlew clean build
```

Which you can then run with:
```
java -jar build/libs/spring-cli-0.0.1-SNAPSHOT.jar
```

For native build:
```
./gradlew clean build nativeCompile
```

NOTE: You need to have `GRAALVM_HOME` pointing to your _graal_ installation

Which you can then run with:
```
build/native/nativeCompile/spring
```

TIP: There is a CI workflow which builds native binaries for linux, macos and windows.
     Published artifacts in CI workflow will get removed daily so take it from
     a latest run which is scheduled nightly.


=== Building Documentation

```
cd docs
../gradlew antora
```

Output is in `./build/site`


=== Shell Completion

Shell completion for `bash` can be generate with `completion bash` command:

```
$ source <(spring completion bash)
```
