= Action Files

Action files are what powers xref:user-command-guide.adoc[user defined commands].
These files are written in YAML format and are stored in the directory that defines the command.

See the documentation on xref:user-command-guide.adoc#_structure[Action file Structure] for more information on the directory struture for user defined commands.

Each file contains a series of actions that are executed in the order they are defined in the file.
An action performs a task that is commonly needed for help developers add code and configuration to their current project.
An action can run another executable application, which helps automate development tasks such as deployment using a vendor's CLI application.

There can be mulitple action files in a directory and they are evaluated in alphabetical order.  **NOTE:** This may change.

There are only a few actions currently, but many more have been prototypes and will be available soon.

The list of actions are:

* *generate* - Create a new file
* *inject* - Inject text in a specific location in an existing file
* *inject-maven-dependency* - Add a maven dependency to the current pom.xml file.
* *inject-maven-plugin* - Add a maven plugin to the current pom.xml file
* *inject-properties* - Add properties to a Java properties file.
* *exec* - Execute another program.

