= Adding To Existing Projects

There are two ways to add code to existing projects

* Using the command `boot add`
* Using user defined commands

== Overview of the boot add command

The `boot add` command will intelligently merge an existing project into your current project.
The code of the existing project is located in a source code repository.
The existing project that is to be merged is checked out into a temporary directory and it's package structure is refactored to match your current project.
Then all code and configuration is copied over from the temporary location, creating new files or updating existing ones as needed.

== Overview of user defined commands

You can register user defined commands with the shell.
Adding code or configuration to an existing project is done through the use of action files that contain instructions of what code or configuration is to be generated and how it is to be incorporated into the current project.
The template engine is Handlebars and is used to model the contents of the code or configuration to be added to a new file or injected into an existing file.
Actions can be conditionally executed and can also execute shell actions.

