= Creating New Projects

When running the command `spring boot new` a simple web application is created.

To create other types of applications you need to pass an additional argument to the `spring boot new` command that specifies the location of the source code for the project you want to create.

You can specify the type of application to create using the name of a registered project or a URL.

There are a few command line options to the `spring boot new` command that let you specify the project name, package name and the location in the filesystem to create the new project.

The following sections go over these topics one by one.

== Creating by name

By default, a project catalog based off the official Spring Getting Started Guides is registered with the shell.  A project catalog contains a list of name and URL pairs.

Executing the command

```
spring catalog list
```

shows the list of project catalogs registered with the shell.

```
┌────┬──────────────────────────────────────────────┬───────────────────────┬───────────────────┐
│Name│URL                                           │Description            │Tags               │
├────┼──────────────────────────────────────────────┼───────────────────────┼───────────────────┤
│gs  │https://github.com/rd-1-2022/spring-gs-catalog│Getting Started Catalog│[java-11, boot-2.7]│
└────┴──────────────────────────────────────────────┴───────────────────────┴───────────────────┘
```

Executing the command

```
spring project list
```

shows the list of projects that are available to create.  Each project has a name that can be passed to `spring boot new`

```
┌─────────────┬────────────────────────────────────────────────────────┬─────────────────────┬───────┬───────────────┐
│Name         │URL                                                     │Description          │Catalog│Tags           │
├─────────────┼────────────────────────────────────────────────────────┼─────────────────────┼───────┼───────────────┤
│web          │https://github.com/rd-1-2022/rpt-rest-service           │Hello, World RESTful │gs     │[rest, web]    │
│             │                                                        │web service.         │       │               │
├─────────────┼────────────────────────────────────────────────────────┼─────────────────────┼───────┼───────────────┤
│jpa          │https://github.com/rd-1-2022/rpt-spring-data-jpa        │Learn how to work    │gs     │[jpa, h2]      │
│             │                                                        │with JPA data        │       │               │
│             │                                                        │persistence using    │       │               │
│             │                                                        │Spring Data JPA.     │       │               │
├─────────────┼────────────────────────────────────────────────────────┼─────────────────────┼───────┼───────────────┤
│scheduling   │https://github.com/rd-1-2022/rpt-spring-scheduling-tasks│How to schedule tasks│gs     │[scheduling]   │
├─────────────┼────────────────────────────────────────────────────────┼─────────────────────┼───────┼───────────────┤
│config-client│https://github.com/rd-1-2022/rpt-config-client          │Using the Config     │gs     │[config]       │
│             │                                                        │Client library       │       │               │
├─────────────┼────────────────────────────────────────────────────────┼─────────────────────┼───────┼───────────────┤
│eureka       │https://github.com/rd-1-2022/eureka                     │Spring Cloud Eureka  │gs     │[cloud, eureka]│
│             │                                                        │Server               │       │               │
├─────────────┼────────────────────────────────────────────────────────┼─────────────────────┼───────┼───────────────┤
│graphql      │https://github.com/rd-1-2022/rpt-spring-graphql         │Spring GraphQL       │gs     │[graphql]      │
└─────────────┴────────────────────────────────────────────────────────┴─────────────────────┴───────┴───────────────┘



```

To create a new project that using Spring Data JPA, execute the command

```
spring boot new jpa
```

And the application that is in the source code repository URL `https://github.com/rd-1-2022/rpt-spring-data-jpa` will be used.

NOTE: You can also use the name of the project as the argument to the command  `spring boot add`

== Creating by URL

Instead of adding a project to the Spring CLI so as to reference it with a short name, you can use the URL of the project's source repository directly.

For example, to create the Spring JPA project, use the command

[source, bash]
----
spring boot new https://github.com/rd-1-2022/rpt-spring-data-jpa 
----

== Options
The `spring boot new` command takes the following options, which can be seen by executing the command

[source, bash]
----
spring help boot new
----

Which displays

[source, bash]
----
NAME
       boot new - Create a new Spring Boot project from an existing project

SYNOPSIS
       boot new --from String --name String --package-name String --path String

OPTIONS
       --from String
       Create project from existing project name or URL
       [Optional]

       --name String
       Name of the new project
       [Optional]

       --package-name String
       Package name for the new project
       [Optional, default = com.example]

       --path String
       Path
       [Optional]
----

The options not yet shown in this documentation are

* `--name` - that specifies the name of the project, the default value is `demo`.  
* `--package-name` - the package name to refactor to
* `--path`  The path to run the command in, most of the time this is not necessary to specify and the default value is the current working directory.



