= Creating New Projects

When running the command `spring boot new` a simple RESTful web application is created.

To create other types of applications you need to pass an additional argument to the `spring boot new` command that specifies the location of the source code for the project you want to create.

You can specify the type of application to create using the name of a registered project or a URL.

There are a few command line options to the `spring boot new` command that let you specify the project name, package name and the location in the filesystem to create the new project.

The following sections go over these topics one by one.

== Creating by name

By default, a project catalog based off the official Spring Getting Started Guides is registered with the shell.  A project catalog contains a list of name and URL pairs.

Executing the command

```
spring catalog list
```

shows the list of project catalogs registered with the shell.  The project catalog contains a list of projects that can be used with the `boot new` or `boot add` commands.

```
┌────┬──────────────────────────────────────────────┬───────────────────────┬───────────────────┐
│Name│URL                                           │Description            │Tags               │
├────┼──────────────────────────────────────────────┼───────────────────────┼───────────────────┤
│gs  │https://github.com/rd-1-2022/spring-gs-catalog│Getting Started Catalog│[java-11, boot-2.7]│
└────┴──────────────────────────────────────────────┴───────────────────────┴───────────────────┘
```

Executing the command

```
spring project list
```

shows the list of projects that are available to use.  Each project has a name that can be passed to `spring boot new`

```
┌─────────────┬────────────────────────────────────────────────────────┬─────────────────────┬───────┬───────────────┐
│Name         │URL                                                     │Description          │Catalog│Tags           │
├─────────────┼────────────────────────────────────────────────────────┼─────────────────────┼───────┼───────────────┤
│web          │https://github.com/rd-1-2022/rest-service               │Hello, World RESTful │gs     │[rest, web]    │
│             │                                                        │web service.         │       │               │
├─────────────┼────────────────────────────────────────────────────────┼─────────────────────┼───────┼───────────────┤
│jpa          │https://github.com/rd-1-2022/rpt-spring-data-jpa        │Learn how to work    │gs     │[jpa, h2]      │
│             │                                                        │with JPA data        │       │               │
│             │                                                        │persistence using    │       │               │
│             │                                                        │Spring Data JPA.     │       │               │
├─────────────┼────────────────────────────────────────────────────────┼─────────────────────┼───────┼───────────────┤
│scheduling   │https://github.com/rd-1-2022/rpt-spring-scheduling-tasks│How to schedule tasks│gs     │[scheduling]   │
├─────────────┼────────────────────────────────────────────────────────┼─────────────────────┼───────┼───────────────┤
│config-client│https://github.com/rd-1-2022/rpt-config-client          │Using the Config     │gs     │[config]       │
│             │                                                        │Client library       │       │               │
├─────────────┼────────────────────────────────────────────────────────┼─────────────────────┼───────┼───────────────┤
│eureka       │https://github.com/rd-1-2022/eureka                     │Spring Cloud Eureka  │gs     │[cloud, eureka]│
│             │                                                        │Server               │       │               │
├─────────────┼────────────────────────────────────────────────────────┼─────────────────────┼───────┼───────────────┤
│graphql      │https://github.com/rd-1-2022/rpt-spring-graphql         │Spring GraphQL       │gs     │[graphql]      │
└─────────────┴────────────────────────────────────────────────────────┴─────────────────────┴───────┴───────────────┘



```

To create a new project that using Spring Data JPA, execute the command

```
spring boot new jpa
```

And the application that is in the source code repository URL `https://github.com/rd-1-2022/rpt-spring-data-jpa` will be used.

NOTE: You can also use the name of the project as the argument to the command  `spring boot add`

== Creating by URL

Instead of adding a project to the Spring CLI so as to reference it with a short name, you can use the URL of the project's source repository directly.

For example, to create the Spring JPA project, use the command

[source, bash]
----
spring boot new https://github.com/rd-1-2022/rpt-spring-data-jpa 
----

== Options
The `spring boot new` command takes the following options, which can be seen by executing the command

[source, bash]
----
spring boot new --help
----

Which displays

[source, bash]
----
NAME
       boot new - Create a new Spring Boot project from an existing project

SYNOPSIS
       boot new --from String --name String --group-id String --artifact-id String --version String --description String --package-name String --path String --help

OPTIONS
       --from String
       Create project from existing project name or URL
       [Optional]

       --name String
       Name of the new project
       [Optional]

       --group-id String
       Group ID of the new project
       [Optional]

       --artifact-id String
       Artifact ID of the new project
       [Optional]

       --version String
       Version of the new project
       [Optional]

       --description String
       Description of the new project
       [Optional]

       --package-name String
       Package name for the new project
       [Optional]

       --path String
       Path to run the command in, most of the time this is not necessary to specify and the default value is the current working directory.
       [Optional]

       --help or -h
       help for boot new
       [Optional]


----

== Options and Default Values

The most common options to specify are `--name` and `--group-id`.
By specifying just the `--name` option, the `artifactId` will default to the value of the `--name` option.
For example

[source, bash]
----
spring boot new --name myapp
Cloning project from https://github.com/rd-1-2022/rest-service
Created project in directory 'myapp'
----

Looking into the generated `pom.xml` the name `myapp` is used as the `artifactId` and the `name` of the project

[source, xml]
----
	<groupId>com.example</groupId>
	<artifactId>myapp</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>myapp</name>
	<description>RESTful web application</description>
----

Adding the option `--groupid` will not only change the value of the `groupId` tag, but also the package name.
A refactoring of the project to the new package name will be performed.
For example:

[source, bash]
----
$ spring boot new --name myapp --group-id com.xkcd
Cloning project from https://github.com/rd-1-2022/rest-service
Refactoring package to com.xkcd.myapp
Created project in directory 'myapp'
----

The generated `pom.xml` contains

[source, xml]
----
	<groupId>com.xkcd</groupId>
	<artifactId>myapp</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>myapp</name>
	<description>RESTful web application</description>
----

and the directory structure of the project is

[source]
----
$ tree myapp/
myapp/
├── LICENSE
├── mvnw
├── mvnw.cmd
├── pom.xml
├── README.adoc
└── src
    ├── main
    │   └── java
    │       └── com
    │           └── xkcd
    │               └── myapp
    │                   ├── Application.java
    │                   └── greeting
    │                       ├── GreetingController.java
    │                       └── Greeting.java
    └── test
        └── java
            └── com
                └── xkcd
                    └── myapp
                        └── greeting
                            └── GreetingControllerTests.java

----


