= Front Matter properties

The Front Matter section is YAML between triple-dashed lines and must be the first content in the file.
Here is a simple example

```
---
action:
  generate: hello.txt
---
Hello {{user-name}} at {{now}} on {{os-name}}.
```

The front matter section starts with the `action` field.  The available optios for nested fields are:

* `inject` - Adds content *into* an existing file
* `exec` - Execute a shell command
* `recipe` - Execute a recipie such as adding a maven dependency, or adding content to a property file.  (TBD)
* TBD...

== Exec

The basic form to execute a shell command is

```
---
action:
  exec:
    args:
      - mkdir
      - "{{tmp-dir}}/scratch"
---
```

Arguments are specified in an array.
Each value of the array is evaluated using the template engine.

The template engine variable `tmp-dir` is defined by default and is the value of the Java System Property `java.io.tmpdir`.

=== Redirecting output

TBD

=== Adding to the template engine model
Sometime you would like to execute a program use its output to define a template engine variable.

The `define` section under `exec` lets you perform this task.
It allows you to define a `jsonPath` expression to select from the output if it is JSON.
This is common output format in many commnand line utilities.

Here is an example.  In the Action File named `00-define-var.yml` the contents are:

```
---
action:
  exec:
    define:
      name: phone-type
      jsonPath: $.phoneNumbers[:1].type
    args:
      - echo
      - '{ "firstName": "John", "lastName": "doe", "age": 26, "address": { "streetAddress": "naist street", "city": "Nara", "postalCode": "630-0192" }, "phoneNumbers": [ { "type": "iPhone", "number": "0123-4567-8888" }, { "type": "home", "number": "0123-4567-8910" } ] }'
---
```

The variable named `phone-type` will be defined as the output from applying the https://github.com/json-path/JsonPath[JSON Path expression] to the output of the command.
In this case, a simple `echo` of JSON is done but in a more realistic case, it would be the output of a command line utility.

Since the file name starts with `00` it will be executed before the file `10-use-var.txt` which is shown below and makes use of the `phone-type` variable.

```
---
action:
  generate: hello.txt
---
Hello {{phone-type.[0]}}
```
