= Getting Started

Creating a new project is as simple as typing `spring boot new`

[source, bash]
----
spring boot new
----

The output will be
[source, bash]
----
Cloning project from https://github.com/rd-1-2022/rest-service
Created project in directory 'rest-service'
----

`**Note**` If the CLI seems to be stuck at the cloning step, you might be hitting GitHub rate limiting.  Use the command `spring github auth login` to authenticate.
 
You can now `cd` into the `rest-service` directory and build and run the application, which is a simple web application with a single endpoint by default.

[source, bash]
----
cd rest-service
./mvnw spring-boot:run
----

Then in another terminal windows, interact with the endpoint using curl.

[source, bash]
----
curl http://localhost:8080/greeting
----

which returns the default 'Hello World' greeting

[source, bash]
----
{"id":1,"content":"Hello, World!"}
----

The README.adoc file in the new project contains more information on how the web applications works.

== Next steps

The section xref:creating-new-projects.adoc[Creating New Projects] shows you how to create applications other than the default application.

The section xref:adding-to-existing-projects.adoc[Adding To Existing Projects] shows you how to add additional applications into your current working project.