= Getting Started

Creating a new project is as simple as typing `spring boot new`

[source, bash]
----
spring boot new
----

The output will be
[source, bash]
----
Using project name demo
Using package name com.example
Cloning project from https://github.com/rd-1-2022/rpt-rest-service

Project demo created in directory demo
----
 

 
You can now cd into the `demo` directory and build and run the application, which is a simple web application with a single endpoint by default.

[source, bash]
----
cd demo
./mnvw spring-boot:run
----

Then in another terminal windows, interact with the endpoint using curl.

[source, bash]
----
curl http://localhost:8080/greeting
----

which returns the default 'Hello World' greeting

[source, bash]
----
{"id":1,"content":"Hello, World!"}
----

The README.adoc file in the new project contains more information on how the web applications works.

== Interactive mode

In addition to running the Spring Boot uber-jar via an alias or running the native binary using `spring` at the command line, you can enter an interactive mode where the Spring CLI will remain up and running.  In this case you do not need to add the `spring` keyword to execute the commands.

The interactive mode provides command option completion but you can also rely on positional option values.

== Command Completion

In non-interactive mode, you can get command completion in your shell by executing the following:

[source, bash]
----
source <(spring completion bash)
----