= Spring CLI

The goal of the Spring CLI is to increase your productivity when creating new projects and adding functionality to existing projects. It does this by providing the following high-level features.

1. The command `boot new` clones an external project and performs a package refactoring to your chosen package name. You can also specify the new project’s group id, artifact id, and version

2. The command `boot add` will add an external project to your current project. It will perform an intelligent merge of project dependencies, plug-ins, annotations, application configuration files, and refactoring of the external project code into your current project’s package structure.

3. User-provided `commands` are defined declaratively and live side by side with your code to help you perform everyday tasks on your current project. For example, creating a new controller with tests, adding new dependencies, code, and configuration files for specific functionality such as test container support, or creating configuration files for your platform or CI system. User-provided commands often leverage a template engine of your choice to perform code generation that can create new files or update existing files.

By basing the `boot new` and `boot add` commands on "Plain Old Java Projects" hosted on GitHub or GitLab, it is easy for companies to define a standard set of projects that use a company's preferred libraries and coding styles. By providing a `README.md` file in these projects, it allows for an obvious starting point for education about a particular library or approach to programming.  For example, executing the command `boot add jpa` would result in not just code added to the current project, but aldo a file named `README-jpa.md`.

User-provided commands are well suited for performing smaller, repetitive coding tasks during the development process. These command definitions can live side by side with the code so that anyone on the development team can contribute a new command or improve an existing command.   By having commands living side by side with the code, contributing to the project is a simple procedure as there is no other artifact or project to create, update and publish.

