= Installation

The Spring CLI is available in various formats allowing user to pick their favourite installation method.

[tabs]
====
Windows::
+
--
Manually:::

Download the pre-compiled binary from the https://github.com/spring-projects-experimental/spring-cli/releases[Release Page].
_spring-cli-standalone-<version>-windows.x86_64.zip_ is based on JDK's _jlink_ and thus doesn't need a JDK installation.
_spring-cli-installer-<version>-windows-x86_64.msi_ is an installer and based on _zip_ file mentioned previously.

--

Linux::
+
--
Manually:::

Download the pre-compiled binary from the https://github.com/spring-projects-experimental/spring-cli/releases[Release Page].
_spring-cli-standalone-<version>-linux.x86_64.zip_ is based on JDK's _jlink_ and thus doesn't need a JDK installation.
_spring-cli-installer-<version>-1.x86_64.rpm_ and _spring-cli-installer_<version>-1_amd64.deb_ are installers and based on _zip_ file mentioned previously.

Homebrew Tap:::

[source]
----
brew tap spring-projects-experimental/spring-cli
brew install spring-cli
----
--

Mac::
+
--
Manually:::

Download the pre-compiled binary from the https://github.com/spring-projects-experimental/spring-cli/releases[Release Page].
_spring-cli-standalone-<version>-osx.x86_64.zip_ is based on JDK's _jlink_ and thus doesn't need a JDK installation.

Homebrew Tap:::

[source]
----
brew tap spring-projects-experimental/spring-cli
brew install spring-cli
----
--

Generic::
+
--
Manually:::

Download the pre-compiled binary from the https://github.com/spring-projects-experimental/spring-cli/releases[Release Page].
_spring-cli-<version>.jar_ is a plain executable jar and need an existing JDK 17 installation.
_spring-cli-<version>.zip_ contains executable jar and scripts for unix and windows and need an
existing JDK 17 installation.
--

====
