= Installation

The Spring CLI is available in various formats that let you pick your favorite installation
method. Downloadable artifacts are available from the
https://github.com/spring-projects/spring-cli/releases[Release Page].

== Binary Release
[tabs]
====
Windows::
+
--
Manually:::

* _spring-cli-standalone-<version>-windows.x86_64.zip_ - bundled _x86_ JDK
* _spring-cli-installer-<version>-windows-x86_64.msi_ - _msi_ installation with bundled _x86_ JDK

--

Linux::
+
--
Manually:::

* _spring-cli-standalone-<version>-linux.x86_64.zip_ - bundled _x86_ JDK
* _spring-cli-installer-<version>-1.x86_64.rpm_ - _rpm_ installation with bundled _x86_ JDK
* _spring-cli-installer_<version>-1_amd64.deb_ - _dep_ installation with bundled _x86_ JDK

Homebrew Tap:::

[source]
----
brew tap spring-cli-projects/spring-cli
brew install spring-cli
----
--

Mac::
+
--
Manually:::

* _spring-cli-standalone-<version>-osx.x86_64.zip_ - bundled _x86_ JDK
* _spring-cli-standalone-<version>-osx.aarch64.zip_ - bundled _arm_ JDK

Homebrew Tap:::

The Tap formula chooses between _x86_ and _aarch64_, depending on your brew setup.

[source]
----
brew tap spring-cli-projects/spring-cli
brew install spring-cli
----
--

Generic::
+
--
Manually:::

* _spring-cli-<version>.jar_ - plain fat jar, needs separate JDK17 installation
* _spring-cli-<version>.zip_ - plain fat jar with start scripts, needs separate JDK17 installation
--

====

== Getting Snapshot Binaries
Latest snapshot binaries are available in a https://github.com/spring-projects/spring-cli/releases/tag/early-access[GitHub Releases early-access].

You can also build the uber-jar from source code, as described <<installation-build-instructions,later on this page>>.

== Building from source
=== Java 17 Installation Required

Even if you use the Spring CLI on a Java 11 or Java 8 project, the CLI itself needs to have access to an installation of Java 17.

Create a `JAVA_HOME` environment variable that points to your Java 17 installation.
For example, for `bash` shells, you can run the following commands:

```
export JAVA_HOME=jdk-install-dir
export PATH=$JAVA_HOME/bin:$PATH
```

This is required by https://github.com/openrewrite/rewrite[OpenRewrite], which is used internally.

[[installation-build-instructions]]
=== Build Instructions

To build the jar yourself, run the following commands:

```
git clone https://github.com/spring-projects/spring-cli $HOME/temp/spring-cli

cd $HOME/temp/spring-cli

./gradlew clean build -x test
```

Now create an alias to invoke the CLI with a command of 'spring':

[source, bash, subs="attributes"]
----
alias spring='java -jar $HOME/temp/spring-cli/build/libs/spring-cli-{project-version}.jar'
----

== Interactive Mode

In addition to running the Spring Boot uber-jar with an alias or running the native binary by using `spring` at the command line, you can enter an interactive mode where the Spring CLI continues to run. In this case, you need not add the `spring` keyword to run the commands.

The interactive mode provides command option completion, but you can also rely on positional option values.

== Command Completion

In non-interactive mode, you can get command completion in your shell by running the following command:

[source, bash, subs="attributes"]
----
eval "$(java -jar $HOME/temp/spring-cli/build/libs/spring-cli-{project-version}.jar completion bash)"
----

NOTE: The Homebrew formula sets bash completion if you have configured https://docs.brew.sh/Shell-Completion.

== Getting Help

The `spring help` command shows help for all the commands.

To get help on a specific command, type `spring help` and the command plus sub-command name -- for example, `spring help boot new`.
