= Installation

The Spring CLI is available as a native binary for Windows, Mac and Linux as well as a Spring Boot uber-jar.  

As the project is evolving quickly in the early days, you can download the Spring Boot uber-jar, Linux and Mac native binaries from the output of GitHub's Continuous Integration Action. 


* https://github.com/spring-projects-experimental/spring-cli/actions/workflows/ci.yml[Download CI artifacts here].  The uber-jar is in the `artifacts.zip` file


When available,  https://github.com/spring-projects-experimental/spring-cli/actions/workflows/release-milestone.yml[Download Milestone Releases here]


Follow the instructions on the project's README file https://github.com/spring-projects-experimental/spring-cli#readme[to build the project from source] file.

== Java 17 installation required

Even if you are using the Spring CLI on a Java 11 or Java 8 based project, the CLI itself needs to have access to an installation of Java 17.

Create a `JAVA_HOME` environment variable that points to your Java 17 installation.

This is required by https://github.com/openrewrite/rewrite[OpenRewrite], which is used internally.

== Setting up your PATH or alias

If you have downloaded the Spring Boot uber-jar, create the following alias with the directory appropriate for you download path.

[source, bash]
----
alias spring='java -jar /home/mark/downloads/spring-cli-0.0.1-SNAPSHOT.jar'
----

If you have downloaded the native binary, please add the directory to your `$PATH`.

== Interactive mode

In addition to running the Spring Boot uber-jar via an alias or running the native binary using `spring` at the command line, you can enter an interactive mode where the Spring CLI will remain up and running.  In this case you do not need to add the `spring` keyword to execute the commands.

The interactive mode provides command option completion but you can also rely on positional option values.

== Command Completion

In non-interactive mode, you can get command completion in your shell by executing the following:

[source, bash]
----
source <(spring completion bash)
----

== Getting Help

The command `spring help` will show help for all the commands.  

To get help on a specific command, just type `spring help` and the command plus sub-command name, e.g. `spring help boot new`